# markdown: redcarpet
markdown: kramdown
highlighter: pygments
permalink: /:title

url: http://manishgcs.github.io
baseurl: 

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

